appversion: v1.0.0
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      NodePort: 30001
<<<<<<< HEAD:kubernetes/Service.yaml
      
        
=======
        
>>>>>>> bd946a921fba9f109de21d99f9b557f543a0390e:kubernetes/service.yaml
